// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgDurxVitRg5o18VfBp98rWA104DSm7Z8',
    appId: '1:1095896133603:web:229e781d33b6dc9832bad6',
    messagingSenderId: '1095896133603',
    projectId: 'food-donation-e0277',
    authDomain: 'food-donation-e0277.firebaseapp.com',
    storageBucket: 'food-donation-e0277.appspot.com',
    measurementId: 'G-E4VKXQ13KY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYKhpSzrDcFzsg8VacJZqdCnTGi204IE0',
    appId: '1:1095896133603:android:c3cb1a6b5a9c90b732bad6',
    messagingSenderId: '1095896133603',
    projectId: 'food-donation-e0277',
    storageBucket: 'food-donation-e0277.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCiVahaIPQG170eazQsijmpBNT0MhU-oXg',
    appId: '1:1095896133603:ios:e5448ff69ac2cd0232bad6',
    messagingSenderId: '1095896133603',
    projectId: 'food-donation-e0277',
    storageBucket: 'food-donation-e0277.appspot.com',
    iosBundleId: 'com.example.foodDonation',
  );
}